# Generated by Django 4.2 on 2023-05-30 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calories_counter", "0004_foods_meals_id_meals_then_eaten_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calories", models.DecimalField(decimal_places=2, max_digits=6)),
                ("protein", models.DecimalField(decimal_places=2, max_digits=6)),
                ("fat", models.DecimalField(decimal_places=2, max_digits=6)),
                ("carbs", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="FoodName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "then_eaten",
                    models.CharField(
                        choices=[
                            ("snack", "Snack"),
                            ("dinner", "Dinner"),
                            ("before lunch", "Before Lunch"),
                            ("before sleep", "Before Sleep"),
                            ("after workout", "After Workout"),
                            ("other", "Other"),
                            ("before dinner", "Before Dinner"),
                            ("lunch", "Lunch"),
                            ("before workout", "Before Workout"),
                            ("breakfast", "Breakfast"),
                        ],
                        default="Snack",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="meals",
            name="user",
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
        migrations.DeleteModel(
            name="Foods",
        ),
        migrations.DeleteModel(
            name="Meals",
        ),
        migrations.AddField(
            model_name="food",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calories_counter.meal"
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="calories_counter.foodname",
            ),
        ),
    ]
