# Generated by Django 4.2 on 2023-06-05 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calories_counter", "0014_alter_meal_then_eaten"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("before lunch", "Before Lunch"),
                    ("dinner", "Dinner"),
                    ("before dinner", "Before Dinner"),
                    ("snack", "Snack"),
                    ("other", "Other"),
                    ("after workout", "After Workout"),
                    ("before sleep", "Before Sleep"),
                    ("before workout", "Before Workout"),
                    ("lunch", "Lunch"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("female", "Female"), ("male", "Male")], max_length=6
            ),
        ),
    ]
