# Generated by Django 4.2 on 2023-06-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0016_remove_food_name_alter_meal_then_eaten_food_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="name",
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before dinner", "Before Dinner"),
                    ("before sleep", "Before Sleep"),
                    ("supplements", "Supplements"),
                    ("before workout", "Before Workout"),
                    ("snack", "Snack"),
                    ("lunch", "Lunch"),
                    ("breakfast", "Breakfast"),
                    ("other", "Other"),
                    ("dinner", "Dinner"),
                    ("after workout", "After Workout"),
                    ("before lunch", "Before Lunch"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calories_counter.foodname",
            ),
        ),
    ]
