# Generated by Django 4.2 on 2023-06-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0017_remove_food_name_alter_meal_then_eaten_food_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="name",
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before sleep", "Before Sleep"),
                    ("snack", "Snack"),
                    ("after workout", "After Workout"),
                    ("before dinner", "Before Dinner"),
                    ("before lunch", "Before Lunch"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("supplements", "Supplements"),
                    ("other", "Other"),
                    ("breakfast", "Breakfast"),
                    ("before workout", "Before Workout"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
    ]
