# Generated by Django 4.2 on 2023-06-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0018_remove_food_name_alter_meal_then_eaten_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="food_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calories_counter.foodname",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before workout", "Before Workout"),
                    ("after workout", "After Workout"),
                    ("before lunch", "Before Lunch"),
                    ("other", "Other"),
                    ("supplements", "Supplements"),
                    ("before dinner", "Before Dinner"),
                    ("before sleep", "Before Sleep"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("snack", "Snack"),
                    ("breakfast", "Breakfast"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
    ]
