# Generated by Django 4.2 on 2023-06-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0020_foodname_food_alter_food_food_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodname",
            name="food",
        ),
        migrations.AlterField(
            model_name="food",
            name="food_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calories_counter.foodname",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before dinner", "Before Dinner"),
                    ("dinner", "Dinner"),
                    ("snack", "Snack"),
                    ("lunch", "Lunch"),
                    ("other", "Other"),
                    ("breakfast", "Breakfast"),
                    ("supplements", "Supplements"),
                    ("before sleep", "Before Sleep"),
                    ("after workout", "After Workout"),
                    ("before lunch", "Before Lunch"),
                    ("before workout", "Before Workout"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("female", "Female"), ("male", "Male")], max_length=6
            ),
        ),
    ]
