# Generated by Django 4.2 on 2023-06-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calories_counter",
            "0023_remove_foodname_food_alter_meal_then_eaten_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="food_name",
        ),
        migrations.AddField(
            model_name="food",
            name="name",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="food_name",
                to="calories_counter.foodname",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before lunch", "Before Lunch"),
                    ("snack", "Snack"),
                    ("supplements", "Supplements"),
                    ("after workout", "After Workout"),
                    ("before workout", "Before Workout"),
                    ("before sleep", "Before Sleep"),
                    ("dinner", "Dinner"),
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("before dinner", "Before Dinner"),
                    ("other", "Other"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
    ]
