# Generated by Django 4.2 on 2023-06-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0025_foodname_food_alter_meal_then_eaten_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="name",
            new_name="food_name",
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before lunch", "Before Lunch"),
                    ("lunch", "Lunch"),
                    ("snack", "Snack"),
                    ("before workout", "Before Workout"),
                    ("before dinner", "Before Dinner"),
                    ("other", "Other"),
                    ("before sleep", "Before Sleep"),
                    ("breakfast", "Breakfast"),
                    ("dinner", "Dinner"),
                    ("supplements", "Supplements"),
                    ("after workout", "After Workout"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
    ]
