# Generated by Django 4.2 on 2023-06-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calories_counter",
            "0026_rename_name_food_food_name_alter_meal_then_eaten_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before dinner", "Before Dinner"),
                    ("dinner", "Dinner"),
                    ("breakfast", "Breakfast"),
                    ("other", "Other"),
                    ("before sleep", "Before Sleep"),
                    ("before lunch", "Before Lunch"),
                    ("after workout", "After Workout"),
                    ("before workout", "Before Workout"),
                    ("snack", "Snack"),
                    ("supplements", "Supplements"),
                    ("lunch", "Lunch"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("female", "Female"), ("male", "Male")], max_length=6
            ),
        ),
    ]
