# Generated by Django 4.2 on 2023-06-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calories_counter",
            "0028_remove_food_food_name_alter_meal_then_eaten_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("after workout", "After Workout"),
                    ("breakfast", "Breakfast"),
                    ("before dinner", "Before Dinner"),
                    ("other", "Other"),
                    ("before sleep", "Before Sleep"),
                    ("before lunch", "Before Lunch"),
                    ("snack", "Snack"),
                    ("dinner", "Dinner"),
                    ("lunch", "Lunch"),
                    ("before workout", "Before Workout"),
                    ("supplements", "Supplements"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
    ]
