# Generated by Django 4.2 on 2023-06-05 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "calories_counter",
            "0028_remove_food_food_name_alter_meal_then_eaten_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before dinner", "Before Dinner"),
                    ("snack", "Snack"),
                    ("dinner", "Dinner"),
                    ("breakfast", "Breakfast"),
                    ("before sleep", "Before Sleep"),
                    ("before lunch", "Before Lunch"),
                    ("supplements", "Supplements"),
                    ("lunch", "Lunch"),
                    ("after workout", "After Workout"),
                    ("before workout", "Before Workout"),
                    ("other", "Other"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
    ]
