# Generated by Django 4.2 on 2023-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0029_alter_food_user_alter_meal_then_eaten_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before dinner", "Before Dinner"),
                    ("supplements", "Supplements"),
                    ("other", "Other"),
                    ("snack", "Snack"),
                    ("dinner", "Dinner"),
                    ("lunch", "Lunch"),
                    ("before lunch", "Before Lunch"),
                    ("before workout", "Before Workout"),
                    ("after workout", "After Workout"),
                    ("before sleep", "Before Sleep"),
                    ("breakfast", "Breakfast"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
    ]
