# Generated by Django 4.2 on 2023-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0031_alter_meal_date_alter_meal_then_eaten_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(default="Snack", max_length=50),
        ),
    ]
