# Generated by Django 4.2 on 2023-06-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0031_alter_meal_then_eaten"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before sleep", "Before Sleep"),
                    ("after workout", "After Workout"),
                    ("dinner", "Dinner"),
                    ("before dinner", "Before Dinner"),
                    ("supplements", "Supplements"),
                    ("lunch", "Lunch"),
                    ("breakfast", "Breakfast"),
                    ("other", "Other"),
                    ("before workout", "Before Workout"),
                    ("snack", "Snack"),
                    ("before lunch", "Before Lunch"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
    ]
