# Generated by Django 4.2 on 2023-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0033_remove_food_name_food_food_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before sleep", "Before Sleep"),
                    ("after workout", "After Workout"),
                    ("before workout", "Before Workout"),
                    ("breakfast", "Breakfast"),
                    ("before dinner", "Before Dinner"),
                    ("supplements", "Supplements"),
                    ("snack", "Snack"),
                    ("before lunch", "Before Lunch"),
                    ("other", "Other"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
    ]
