# Generated by Django 4.2 on 2023-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0034_alter_meal_then_eaten"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before workout", "Before Workout"),
                    ("other", "Other"),
                    ("lunch", "Lunch"),
                    ("before lunch", "Before Lunch"),
                    ("after workout", "After Workout"),
                    ("breakfast", "Breakfast"),
                    ("supplements", "Supplements"),
                    ("snack", "Snack"),
                    ("before sleep", "Before Sleep"),
                    ("dinner", "Dinner"),
                    ("before dinner", "Before Dinner"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("female", "Female"), ("male", "Male")], max_length=6
            ),
        ),
        migrations.DeleteModel(
            name="FoodName",
        ),
    ]
