# Generated by Django 4.2 on 2023-06-07 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calories_counter", "0035_alter_meal_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                choices=[
                    ("before sleep", "Before Sleep"),
                    ("other", "Other"),
                    ("before lunch", "Before Lunch"),
                    ("lunch", "Lunch"),
                    ("snack", "Snack"),
                    ("breakfast", "Breakfast"),
                    ("before workout", "Before Workout"),
                    ("dinner", "Dinner"),
                    ("after workout", "After Workout"),
                    ("supplements", "Supplements"),
                    ("before dinner", "Before Dinner"),
                ],
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
