# Generated by Django 4.2 on 2023-06-13 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calories_counter", "0046_alter_meal_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
