# Generated by Django 4.2.2 on 2023-06-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calories_counter",
            "0048_remove_food_meal_food_date_food_then_eaten_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userinformation",
            name="weight_history",
            field=models.TextField(blank=True, default=""),
        ),
    ]
