# Generated by Django 4.2.2 on 2023-06-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0050_remove_userinformation_weight_history_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("weight", models.FloatField()),
                (
                    "user_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_histories",
                        to="calories_counter.userinformation",
                    ),
                ),
            ],
        ),
    ]
