# Generated by Django 4.2 on 2023-06-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel_app", "0002_quote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.CharField(
                blank=True, default="Unknown", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
