# Generated by Django 4.2 on 2023-06-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_blog", "0003_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyCircumferenceMeasurements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("neck_size", models.DecimalField(decimal_places=2, max_digits=6)),
                ("chest_size", models.DecimalField(decimal_places=2, max_digits=6)),
                ("waist_size", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "left_bicep_size",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "right_bicep_size",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "left_forearm_size",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "right_forearm_size",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "left_thigh_size",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "right_thigh_size",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("left_calf_size", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "right_calf_size",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
            ],
        ),
    ]
