# Generated by Django 4.2 on 2023-06-12 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calories_blog", "0004_bodycircumferencemeasurements"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BodyCircumferenceMeasurements",
        ),
    ]
