# Generated by Django 4.2 on 2023-04-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calories_counter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealfood",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
