# Generated by Django 4.2 on 2023-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0005_food_foodname_meal_remove_meals_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="weight_measure",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before lunch", "Before Lunch"),
                    ("other", "Other"),
                    ("before sleep", "Before Sleep"),
                    ("breakfast", "Breakfast"),
                    ("after workout", "After Workout"),
                    ("lunch", "Lunch"),
                    ("before dinner", "Before Dinner"),
                    ("dinner", "Dinner"),
                    ("before workout", "Before Workout"),
                    ("snack", "Snack"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("female", "Female"), ("male", "Male")], max_length=6
            ),
        ),
    ]
