# Generated by Django 4.2 on 2023-05-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0008_meal_date_alter_meal_then_eaten"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinformation",
            name="user",
        ),
        migrations.AddField(
            model_name="userinformation",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userinformation",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userinformation",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userinformation",
            name="user_photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("before workout", "Before Workout"),
                    ("before dinner", "Before Dinner"),
                    ("before lunch", "Before Lunch"),
                    ("breakfast", "Breakfast"),
                    ("snack", "Snack"),
                    ("after workout", "After Workout"),
                    ("before sleep", "Before Sleep"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
    ]
