# Generated by Django 4.2 on 2023-06-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calories_counter",
            "0010_userinformation_user_alter_meal_then_eaten_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinformation",
            name="age",
        ),
        migrations.AddField(
            model_name="userinformation",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("dinner", "Dinner"),
                    ("after workout", "After Workout"),
                    ("snack", "Snack"),
                    ("before lunch", "Before Lunch"),
                    ("other", "Other"),
                    ("lunch", "Lunch"),
                    ("before sleep", "Before Sleep"),
                    ("before workout", "Before Workout"),
                    ("breakfast", "Breakfast"),
                    ("before dinner", "Before Dinner"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
    ]
