# Generated by Django 4.2 on 2023-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0015_food_user_alter_meal_then_eaten_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="name",
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("dinner", "Dinner"),
                    ("lunch", "Lunch"),
                    ("supplements", "Supplements"),
                    ("before workout", "Before Workout"),
                    ("breakfast", "Breakfast"),
                    ("snack", "Snack"),
                    ("before lunch", "Before Lunch"),
                    ("after workout", "After Workout"),
                    ("before sleep", "Before Sleep"),
                    ("other", "Other"),
                    ("before dinner", "Before Dinner"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="name",
            field=models.ManyToManyField(to="calories_counter.foodname"),
        ),
    ]
