# Generated by Django 4.2 on 2023-06-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0019_food_food_name_alter_meal_then_eaten"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodname",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calories_counter.food",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="food_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foods",
                to="calories_counter.foodname",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before workout", "Before Workout"),
                    ("supplements", "Supplements"),
                    ("breakfast", "Breakfast"),
                    ("before lunch", "Before Lunch"),
                    ("before sleep", "Before Sleep"),
                    ("snack", "Snack"),
                    ("after workout", "After Workout"),
                    ("before dinner", "Before Dinner"),
                    ("other", "Other"),
                    ("dinner", "Dinner"),
                    ("lunch", "Lunch"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
    ]
