# Generated by Django 4.2 on 2023-06-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0021_remove_foodname_food_alter_food_food_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodname",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calories_counter.food",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="food_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foods",
                to="calories_counter.foodname",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before workout", "Before Workout"),
                    ("dinner", "Dinner"),
                    ("before sleep", "Before Sleep"),
                    ("other", "Other"),
                    ("snack", "Snack"),
                    ("before lunch", "Before Lunch"),
                    ("lunch", "Lunch"),
                    ("breakfast", "Breakfast"),
                    ("before dinner", "Before Dinner"),
                    ("after workout", "After Workout"),
                    ("supplements", "Supplements"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
    ]
