# Generated by Django 4.2 on 2023-06-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0025_foodname_food_alter_meal_then_eaten_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="name",
        ),
        migrations.AddField(
            model_name="food",
            name="food_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("before lunch", "Before Lunch"),
                    ("before workout", "Before Workout"),
                    ("before sleep", "Before Sleep"),
                    ("breakfast", "Breakfast"),
                    ("after workout", "After Workout"),
                    ("snack", "Snack"),
                    ("before dinner", "Before Dinner"),
                    ("supplements", "Supplements"),
                    ("other", "Other"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
        migrations.DeleteModel(
            name="FoodName",
        ),
    ]
