# Generated by Django 4.2 on 2023-06-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0028_alter_meal_then_eaten_alter_userinformation_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="then_eaten",
            field=models.CharField(
                choices=[
                    ("before sleep", "Before Sleep"),
                    ("snack", "Snack"),
                    ("breakfast", "Breakfast"),
                    ("before lunch", "Before Lunch"),
                    ("other", "Other"),
                    ("after workout", "After Workout"),
                    ("dinner", "Dinner"),
                    ("lunch", "Lunch"),
                    ("before workout", "Before Workout"),
                    ("supplements", "Supplements"),
                    ("before dinner", "Before Dinner"),
                ],
                default="Snack",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
    ]
