# Generated by Django 4.2 on 2023-06-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calories_counter", "0032_alter_meal_then_eaten"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                choices=[
                    ("before lunch", "Before Lunch"),
                    ("other", "Other"),
                    ("before workout", "Before Workout"),
                    ("before dinner", "Before Dinner"),
                    ("snack", "Snack"),
                    ("dinner", "Dinner"),
                    ("after workout", "After Workout"),
                    ("lunch", "Lunch"),
                    ("supplements", "Supplements"),
                    ("breakfast", "Breakfast"),
                    ("before sleep", "Before Sleep"),
                ],
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("female", "Female"), ("male", "Male")], max_length=6
            ),
        ),
    ]
