# Generated by Django 4.2 on 2023-06-07 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calories_counter", "0039_alter_meal_user_alter_userinformation_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                choices=[
                    ("before lunch", "Before Lunch"),
                    ("lunch", "Lunch"),
                    ("before dinner", "Before Dinner"),
                    ("dinner", "Dinner"),
                    ("other", "Other"),
                    ("before sleep", "Before Sleep"),
                    ("snack", "Snack"),
                    ("before workout", "Before Workout"),
                    ("after workout", "After Workout"),
                    ("breakfast", "Breakfast"),
                    ("supplements", "Supplements"),
                ],
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
    ]
