# Generated by Django 4.2 on 2023-06-13 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calories_counter", "0044_bodycircumferencemeasurements_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodycircumferencemeasurements",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                choices=[
                    ("supplements", "Supplements"),
                    ("other", "Other"),
                    ("before dinner", "Before Dinner"),
                    ("before lunch", "Before Lunch"),
                    ("before workout", "Before Workout"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("breakfast", "Breakfast"),
                    ("before sleep", "Before Sleep"),
                    ("snack", "Snack"),
                    ("after workout", "After Workout"),
                ],
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
