# Generated by Django 4.2 on 2023-06-13 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calories_counter", "0045_alter_bodycircumferencemeasurements_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                choices=[
                    ("after workout", "After Workout"),
                    ("breakfast", "Breakfast"),
                    ("before sleep", "Before Sleep"),
                    ("before workout", "Before Workout"),
                    ("other", "Other"),
                    ("before lunch", "Before Lunch"),
                    ("lunch", "Lunch"),
                    ("before dinner", "Before Dinner"),
                    ("dinner", "Dinner"),
                    ("snack", "Snack"),
                    ("supplements", "Supplements"),
                ],
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
