# Generated by Django 4.2.2 on 2023-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calories_counter", "0049_userinformation_weight_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinformation",
            name="weight_history",
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="gender",
            field=models.CharField(
                choices=[("female", "Female"), ("male", "Male")], max_length=6
            ),
        ),
    ]
