# Generated by Django 4.2 on 2023-06-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("quote", models.CharField(max_length=255)),
            ],
        ),
    ]
