# Generated by Django 4.2 on 2023-06-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel_app", "0003_alter_quote_author_alter_quote_quote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
